#ENC[AES256_GCM,data:wahWARWq,iv:tdnZisxX3EQYaQIz+GEd7po0nVM0p7fCysrtHTaJibw=,tag:dXQeZ6ItJA3udgMufzNcUg==,type:comment]
wifi_ssid: ENC[AES256_GCM,data:o4kyqiC5YyDu8Gt2Cw==,iv:mUJE+geZER/m7pLPMdoINVLgUjJh4LeryPpH7t3dSmk=,tag:P6oKVhqS3GzgzlCxQkIhGQ==,type:str]
wifi_password: ENC[AES256_GCM,data:ZjHkzTzZxJahh+Kd1U4JNB0mdzYeixJ/k/C2GjCj0A1FEGhMKHNqilvrAI/1wJeoZS9d1fRRCimdevcxpp4=,iv:JEW9u/8FfhlpQ5ZrLPOXAF/qijwDUc53xv6fbPz3Oko=,tag:dBF7vUZmGs3aXsLCuZdrIg==,type:str]
wifi_maypen_ssid: ENC[AES256_GCM,data:9nzyP0rbkYkP6cFrB6+ouuE=,iv:Hwzkm2QYefVL1gO0HoGlAOy4VIoY0dyH4NIV4G5aKr0=,tag:1ZA6TOLRzwChnDgawI10ag==,type:str]
wifi_maypen_password: ENC[AES256_GCM,data:H9l2Rq1dxvs=,iv:HGNc77GVexCoseHsulKyWSLmkULz2KEuslB8GAIJN2U=,tag:jQfMa8V3Hg05T1ff9bz4hQ==,type:str]
#ENC[AES256_GCM,data:tZFVe+qycMtLGs2tNyI=,iv:N+HxIutW2iG7V8nw7UDdLxZz9jGTHx3TyYfLiueLnq0=,tag:/+ov0a4bSkWqr/nEe7hCNQ==,type:comment]
web_username: ENC[AES256_GCM,data:e/X8lqZ+Ytw=,iv:/RPD/pndkJf6zT46eM2zgqMwDanmM/FojoiL/iKkkmo=,tag:X1EkWeTQhC0AkvkFmBCkSQ==,type:str]
web_password: ENC[AES256_GCM,data:zBZ2BimNIE+LnwyMcCP7IN5ZJEfiDMnbxWH77YY+j7M=,iv:Zqwg2uzPMsLybpRlb5CfHxJrjx36HJB0L3oR7GwbQAk=,tag:evTpv+UUCNIyD3a44kJDvQ==,type:str]
#ENC[AES256_GCM,data:+oA1Hbtxz+GUmsDAMHCjGI6nivE1,iv:n6jLKuaYINu62ZJlnRR0ouepAi18XuMNIpLDERLmO7k=,tag:lm4057AkODXyvRCy/FMUwA==,type:comment]
ota_password: ENC[AES256_GCM,data:GZQNv2VEmMIxQ91QHSDwmtkg5R13SpLiFBdyJu0BbS0=,iv:EJUOIZeAc24bO177SgbD6ZHXpHgNtdahKvhUEW+3iw8=,tag:w8bemOEHcq24k2wcDY7ZCw==,type:str]
#ENC[AES256_GCM,data:sYOPwTEvZg40IdRIvtFxlu/xm2nrOfg=,iv:y6pLE11CvkiP/pYJh2c996/Eid/VqoJoEVn4lKpk3DI=,tag:ZP6yPC1D4C1qttBa0tO5ww==,type:comment]
api_encryption_key: ENC[AES256_GCM,data:jsmstOrWMwfKzvVNDvW4tVLPfc1grW54+zbnoE0Ofc+oUIfFgiQENIPJPCE=,iv:jswX9x3Wdo1qMkPzbXBcN79/oQzwWjYYuvIwujIHbjE=,tag:L94dbmYQ4iMb9RPKBhGiFA==,type:str]
#ENC[AES256_GCM,data:et2/wfUhXgjnhw==,iv:LFaw1AJAYYpXXAwkbGxTqTh++pOLowctLPxi/zVtEOY=,tag:U0vLcUyjCT12+nrdkGHA+w==,type:comment]
wg-peer-endpoint: ENC[AES256_GCM,data:CbECtDdFKcyE3/0dXI+VGM/0,iv:VwM0TBkJCk0sCtWDx9ZkYK9z3k0uhopzeQoZP/gP8SY=,tag:CO6V0ItpDqFdMZ6oX+jBfA==,type:str]
wg-peer-publickey: ENC[AES256_GCM,data:0vNxK9cHq79o3MMwA9/fxh+EPH22xq+i6UVfGqS5AmsMb8qraGc2PsQFApY=,iv:zUPIe5rSsLCNuxeMBckrAiGQB3X5jPHmbC//Ol3s+rA=,tag:xs+PDqEaYwSnl2FZWN8x7g==,type:str]
wg-socket-ragnarok-privkey: ENC[AES256_GCM,data:hO5nTtQw4Fo1JGPn7/t/WOAAwG4aZAMdQ1HdVQRwd57eEuyOQJ7l+R+GVnI=,iv:P5xpKeA2r2FUylGCx1oZBgEekkW8hPmcbacvE2+xvMc=,tag:5BQlV6w0SK3zPbFnZTpdzQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuN1ZwV2h6bFdLc0QvU0xG
            bmY4Z042YWxxQWsrKzdLVHMvMlNlZ0JPdlhvCjBHWUZGWlcyeDEzWG5pRWlLMU1w
            ODdBUjVYWlFnWlVabW9jbk5qMmh6SGsKLS0tIGFuSmZGblBvL3VzN3JxRHJ0dGVt
            ZUs2SGRtUUdxY2NidzZUakE1UHdVSGcKrlMqo1b82vF1KOVMeRtWqvuyk6cH2xWc
            Jzguqb8VQM+l9XTFsaFFqEeYCfMT7yBAUkEqw5iHWaVnyHzCtOEHIQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tckne6re77p0hw425vjqxlel6h5aw9q060cw8zayw7f7x6p43c9svcxrg0
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEcFhTWlo0emxXTDhlNnpX
            OG42UWJCOCt3bWh3ME5Rc1Z4VFFJUDEwaVQ0ClI1N3NmYjNnQSs3VVMzWnQ1enhh
            UVFscXNIUjBMT29qSGJ3YzhCZTFrZWcKLS0tIEI4dkR4d0JnamNqR2xuODBDdkgw
            SkFqQ0FLSklVcGtQL091bHlKdlovbHcKB7royB7Q7KpyW0cXyfLHwdZiAj2pQMtc
            Mejz/YFOZrHqPMG0HVC12uUVAKqP7ANYVOx0fq6lOs/FP3NlKnJW9Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1yggjnkvxm45ssrlwx56pcps43gzglrvfnqdmv8hxcqsqcuj68v7qdj25sg
    lastmodified: "2026-07-19T20:29:10Z"
    mac: ENC[AES256_GCM,data:8QpNj4qoqfTsfUAD9yNpPjm4vlzqcduXjf1mwukmRWXTJafQ9RzhDe6gTcq4mb+yr10ZhFkZ/9EzjBgBTme5yPlvoLLjlBKt8fr3DoQR5wDSfbhlt9qh6bKIKbWAp6nFghXt1LfC0sb+/qnAdvu632zYmGLvAkN4mIM23YwhzPc=,iv:+FaKMAENTEOji4BZE5PcOW5qrXOaMcqjKta3n/qO20w=,tag:4V0kWIXZfDH3VGdwzLqDig==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.2
