esphome_env: ENC[AES256_GCM,data:J1+DzJ3g1cD5gRqBCzR/GLffqmhUjfBklg7DHLwjSnNrECvayNE25wgKMKtcFaTEW0v4JzbWh5pyzGrV,iv:2uoqJZYjmFAww/4NZZw8VK2UqmT/q7uegxEkbB1P/FM=,tag:J8YfvgjMQBEyDFujVniSNQ==,type:str]
sops:
    age:
        - recipient: age1tckne6re77p0hw425vjqxlel6h5aw9q060cw8zayw7f7x6p43c9svcxrg0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUVZTU2hiS0tkUXRmSjVL
            VXpVOU5ZSTBHdFd4MFo0Z2Z2UCs3YTlBb0JVClI5Q3UzU2ppUlJSKzN4bzRvNWdE
            bDRscWJYNWFvZ2VBc3cxRS9PRVY5cWsKLS0tIDBZSTg5a0pFQXVvalBSeHliTk9E
            T003M0NiQ2Vhbnp6elIwTGtUckpxaXcK/E65r7uizJc5yXb2+SNyKojz4SUJKzim
            5MUD8GAhv3ki+yfs1+hFrezE1q1WSChcnhzLr9+z/wg6Ih+R3DpjNQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1yggjnkvxm45ssrlwx56pcps43gzglrvfnqdmv8hxcqsqcuj68v7qdj25sg
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRMGV6UUhmNlFqNFdYVVl0
            NkdYQXdyUFlUNzhnSGRrOU1kTnVySmFJSVM0CkJLUVNBRUhLaXF1a0NFMTlKQkF2
            SWRWK3pqMGpJcTNuY3EyN0dFU0ZOaEEKLS0tIEp5MVd4MlFiNVdpZ0IrU09nQ3oz
            SjJZVXRvbnRzV1NHVGxVYWFld3h6Y3MKz5qven7l9H9QVVSR8q5B0IaH+4o7Xin0
            jFITaIKzIO71vaAHzxJrshHaHAlUjefvFznjWS+PoBHPcj2a1GLRWQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-07T21:46:00Z"
    mac: ENC[AES256_GCM,data:brhaHjTfIb0GFVb/s7vZAXGQu0cBjx6Nte8KfLn3K8+SIOdPBvbeP3sw0gRLB/ktz3K+wgpYwjamTZUFrRW+ace1LUDFPTffi1qRp7tKs8cm02oIE9DaZ1xQHCzUfblmM9DLG1AXOWSDmZGYh2p0QYRfq3+wmfoQH5cnB4XBsNA=,iv:XsjnpD5O6cZpvcGpE/UMuIYVm+boStmKVlkQdFlkYcs=,tag:vxO5G/Ez3mdsJ5xMpcHQ+g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
