keys:
  - &user_beatlink age1tckne6re77p0hw425vjqxlel6h5aw9q060cw8zayw7f7x6p43c9svcxrg0
  - &host_ragnarok age18a3msuyfem87qzknt6s64z086lt5lptf7fnqsp3wkt27wrl57fas80c86k
  - &host_heimdall age1yggjnkvxm45ssrlwx56pcps43gzglrvfnqdmv8hxcqsqcuj68v7qdj25sg
  - &host_odin age19lxeg27tf95vs67jjh6e68ukf0d9hjyj5q4pcprzrvpwnnt6j3fsvjh4rd
  - &host_thor age1pcsyypcrls76syx5zl6szzw9tmnz602jn9fcxm6d8tc3yld2492qkudxhp
creation_rules:
  - path_regex: secrets/0-common.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_beatlink
        - *host_ragnarok
        - *host_heimdall
        - *host_odin
        - *host_thor
  - path_regex: secrets/1-backup-server.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_beatlink
        - *host_ragnarok
  - path_regex: secrets/2-server.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_beatlink
        - *host_heimdall
  - path_regex: secrets/3-laptop.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_beatlink
        - *host_odin
  - path_regex: secrets/4-phone.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_beatlink
        - *host_thor
