{
    imports = [
        ./calculator.nix
        ./cheese.nix
        ./czkawka.nix
        ./decoder.nix
        ./deluge.nix
        ./drawio.nix
        ./dupeguru.nix
        ./inkscape.nix
        ./libreoffice.nix
        ./screenshot.nix
        ./simple-scan.nix
        ./universal-android-debloater.nix
        ./virt-manager.nix
        ./alarm-clock-applet
        ./pix
    ];
}
