# Plank Dock ###############################################################################################################
# 
# This dock is used for quickly launching applications.
#
# Settings are stored via Dconf but are exported using the 1-export-dconf-settings.sh script in this folder
#
# Launchers are grouped into categories separated via spaces. The spaces are generated by my plank separator script
# https://github.com/BeatLink/Plank-Separator
# X-GNOME-Autostart-Delay=0
###########################################################################################################################################

{ config, lib, pkgs, ... }:
{
    environment.systemPackages = [ pkgs.nemo-with-extensions ];                # Installs Plank from nixpkgs
    programs.fuse.userAllowOther = true;
    home-manager.users.beatlink = { config, pkgs, ... }: {
        home = {
            persistence."/Storage/Apps/System/Nemo" = {
                directories = [
                    ".config/nemo"
                    ".local/share/nemo"
                ];
                allowOther = true;
            };
            file =  {
                ".config/gtk-3.0/bookmarks".text = ''
                    file:///Storage/Files/Documents Documents
                    file:///Storage/Files/Downloads Downloads
                    file:///Storage/Files/eBooks eBooks
                    file:///Storage/Files/Games Games
                    file:///Storage/Files/Music Music
                    file:///Storage/Files/Pictures Pictures
                    file:///Storage/Files/Projects Projects
                    file:///Storage/Files/Sounds Sounds
                    file:///Storage/Files/Videos Videos
                    file:///Storage/Files/VMs VMs
                    file:///Storage/Files/Backups Backups
                    file:///Storage Storage
                    sftp://beatlink@heimdall.technet/Storage Heimdall
                    sftp://beatlink@ragnarok.technet/Storage Ragnarok
                '';
            };
        };
        dconf.enable = true;                                    # Enables dconf which stores plank settings
        imports = [./2-dconf-settings.nix];                     # Imports the dconf settings
    };
}
