# COSMIC Theme ######################################################################################################################################
#
# Halon for COSMIC. The desktop keeps its look in cosmic-config, one file per key under an application id, read from the user's own configuration
# first and from share/cosmic in the system profile otherwise — so the theme ships as system defaults and the Appearance page stays able to write
# over it. The colour keys under ./theme are generated by ./generate-theme.rs, which runs COSMIC's own derivation over Halon's tokens.
#

{ lib, pkgs, ... }:
let
    # Every key COSMIC reads is a file of RON, so the settings written here are spelled out the way the generated ones are.
    keys = {
        # Applying the theme globally symlinks COSMIC's generated CSS over ~/.config/gtk-{3,4}.0/gtk.css and rewrites qt5ct.conf, which is where
        # Halon lives. Off, the daemon takes those files back out again and leaves both toolkits to the dconf and qt5ct settings.
        "com.system76.CosmicTk/v1/apply_theme_global" = "false";
        # Written to org.gnome.desktop.interface whether or not the theme is applied globally, so it has to name the icons Cinnamon uses.
        "com.system76.CosmicTk/v1/icon_theme" = ''"Mint-Y-Aqua"'';
        # Halon is a light theme by choice, matching the Cinnamon session.
        "com.system76.CosmicTheme.Mode/v1/is_dark" = "false";
        "com.system76.CosmicTheme.Mode/v1/auto_switch" = "false";
    };

    # cosmic-settings installs its own defaults on these paths, so this package has to win the collision in the system profile.
    theme = lib.hiPrio (
        pkgs.runCommand "halon-cosmic-theme" { } ''
            mkdir -p $out/share
            cp -r ${./theme} $out/share/cosmic
            chmod -R u+w $out/share/cosmic
            ${lib.concatStrings (
                lib.mapAttrsToList (
                    key: value: "install -Dm444 ${pkgs.writeText "cosmic-key" value} $out/share/cosmic/${key}\n"
                ) keys
            )}
        ''
    );
in
{
    environment.systemPackages = [ theme ];
}
