{
    imports = [
        ./anthem.nix
        ./calibre-web
        ./ckan.nix
        ./freetube.nix
        ./gmusicbrowser.nix
        ./itch.nix
        ./lmms.nix
        ./newsflash.nix
        ./nitrox.nix
        ./picard.nix
        ./playitslowly.nix
        ./quodlibet.nix
        ./steam.nix
        ./stremio.nix
        ./vlc.nix
    ];
}
