# Plank Dock ###############################################################################################################
# 
# This dock is used for quickly launching applications.
#
# Settings are stored via Dconf but are exported using the 1-export-dconf-settings.sh script in this folder
#
# Launchers are grouped into categories seperated via spaces. The spaces are generated by my plank separator script
# https://github.com/BeatLink/Plank-Separator
# X-GNOME-Autostart-Delay=0
###########################################################################################################################################

{ config, lib, pkgs, ... }:
{
    environment.systemPackages = [ pkgs.nemo-with-extensions ];                # Installs Plank from nixpkgs
    programs.fuse.userAllowOther = true;
    home-manager.users.beatlink = { config, pkgs, ... }: {
        home = {
            persistence."/Storage/Apps/System/Nemo" = {
                directories = [
                    ".config/nemo"
                    ".local/share/nemo"
                ];
                allowOther = true;
            };
        };
        dconf.enable = true;                                    # Enables dconf which stores plank settings
        imports = [./2-dconf-settings.nix];                     # Imports the dconf settings

    };
}
