# Cinnamon Settings
#
# This module configures all the settings for the Cinnamon Desktop Environment. Cinnamon settings are stored in dconf.
# It is automatically generated by nixtool's export dconf options so you can change the cinnamon settings then export the changes without editing
# the file manually.
#

{ inputs, pkgs, ... }:
let
    webGreeter = pkgs.callPackage ./web-greeter.nix { };
in
{
    imports = [ ./cinnamon-bump.nix ];

    services = {
        displayManager = {
            logToFile = false;
            logToJournal = false;
            defaultSession = "cinnamon-wayland"; # Per-output scanout buffers, so losing a monitor cannot wedge every head at once
        };
        xserver = {
            enable = true; # Enables X11 Server
            displayManager.lightdm = {
                enable = true; # Enables LightDM Login Manager
                # Puts the graphical session on VT7 instead of VT1. NixOS defaults
                # minimum-vt to 1, which lands X on the same VT as the first getty
                # and makes Ctrl+Alt+F1..F6 unusable. This key is emitted after the
                # module's own, so it wins.
                extraConfig = ''
                    minimum-vt = 7
                '';
                # defaultSession only stamps AccountsService, which web-greeter does not read; without this LightDM
                # has no default and takes the first entry in sessions-directory, where xsessions comes first.
                extraSeatDefaults = ''
                    user-session = cinnamon-wayland
                '';
                greeters.gtk.enable = false; # Defaults on, and its own greeter definition would collide with the one below
                # web-greeter has no NixOS module, so the greeter is named directly
                greeter = {
                    package = webGreeter.xgreeters;
                    name = "web-greeter";
                };
            };
            desktopManager.cinnamon.enable = true; # Enables Cinnamon
            enableCtrlAltBackspace = true; # Enables CTRL+ALT+Backspace for restarting X11
            excludePackages = with pkgs; [ xterm ];
        };
        libinput.enable = true; # Enables Touchpad Functionality
    };
    # web-greeter reads this path unconditionally; it has no XDG or per-user lookup
    environment.etc."lightdm/web-greeter.toml".text = ''
        layouts = [ "us" ]

        [greeter]
        debug-mode = false
        detect-theme-errors = true
        screensaver-timeout = 300
        secure-mode = true
        theme = "gruvbox"
        icon-theme = "Bibata-Modern-Classic" # Named icon-theme, but the greeter only feeds it to XCURSOR_THEME

        [features.battery]
        enabled = true

        # Off because the greeter writes /sys/class/backlight directly, which the lightdm user cannot do
        [features.backlight]
        enabled = false
        value = 10
        steps = 0

        [branding]
        background-images-dir = "/run/current-system/sw/share/backgrounds"
        logo-image = "${webGreeter}/share/icons/hicolor/scalable/apps/com.github.jezerm.web-greeter.svg"
        user-image = "${webGreeter}/share/icons/hicolor/scalable/apps/com.github.jezerm.web-greeter.svg"
    '';

    environment.systemPackages = with pkgs; [
        inputs.halon.packages.${pkgs.stdenv.hostPlatform.system}.halon-theme
        gnome-themes-extra
        libnotify
        ddcutil
        i2c-tools
        brightnessctl
        bibata-cursors # The greeter resolves its cursor through XCURSOR_PATH, which covers the system profile
    ];
    environment.cinnamon.excludePackages = with pkgs; [
        onboard
        gnome-calendar
        gnome-terminal
        warpinator
        celluloid
    ];

    home-manager.users.beatlink = {
        xsession = {
            scriptPath = ".local/share/X11/xsession";
            initExtra = "ERRFILE=$HOME/.local/share/X11/xsession-errors";
        };
        home = {
            packages = with pkgs; [
                #python310
                gnumake
                gcc
            ];
            persistence."/Storage/Apps/System/Cinnamon" = {
                # Loads persistent data for plank
                directories = [
                    ".config/cinnamon"
                    ".config/cinnamon-session"
                    ".local/share/cinnamon"
                ];
                files = [
                    ".config/X-Cinnamon-xdg-terminals.list"
                    ".config/xdg-terminals.list"
                    ".config/mimeapps.list"
                ];

            };
        };
        systemd.user.services = {
            "cinnamon-spice-updater" = {
                Unit = {
                    Description = "Cinnamon Spice Updater";
                    After = "home-beatlink-.local-share-cinnamon.mount";
                };
                Service = {
                    ExecStart = "${pkgs.cinnamon-common}/bin/cinnamon-spice-updater --update-all";
                };
                Install = {
                    WantedBy = [ "default.target" ];
                };
            };
        };
    };
}
