# Cinnamon Settings
#
# This module configures all the settings for the Cinnamon Desktop Environment. Cinnamon settings are stored in dconf-settings.nix.
# It is automatically generated by export-dconf-settings.sh so you can change the cinnamon settings then export the changes without editing
# the file manually.
#

{ pkgs, ... }:
{
    services = {
        displayManager = {
            logToFile = false;
            logToJournal = false;
        };
        xserver = {
            enable = true; # Enables X11 Server
            displayManager.lightdm = {
                enable = true; # Enables LightDM Login Manager
                greeters.gtk = {
                    cursorTheme = {
                        name = "Bibata-Modern-Classic";
                        package = pkgs.bibata-cursors;
                    };
                    iconTheme = {
                        name = "Mint-Y-Aqua";
                        package = pkgs.mint-y-icons;
                    };
                    theme = {
                        name = "Mint-Y-Aqua";
                        package = pkgs.mint-themes;
                    };
                    clock-format = "%H:%M:%S`";
                    indicators = [
                        "~host"
                        "~spacer"
                        "~clock"
                        "~spacer"
                        "~session"
                        "~language"
                        "~a11y"
                        "~power"
                    ];
                };
            };
            desktopManager.cinnamon.enable = true; # Enables Cinnamon
            enableCtrlAltBackspace = true; # Enables CTRL+ALT+Backspace for restarting X11
            excludePackages = with pkgs; [ xterm ];
        };
        libinput.enable = true; # Enables Touchpad Functionality
    };
    environment.systemPackages = with pkgs; [
        gnome-themes-extra
        libnotify
        ddcutil
        i2c-tools
    ];
    environment.cinnamon.excludePackages = with pkgs; [
        onboard
        gnome-calendar
        gnome-terminal
        warpinator
        celluloid
    ];

    home-manager.users.beatlink = {
        imports = [ ./dconf ]; # Imports Cinnamon Dconf Settings
        xsession = {
            scriptPath = ".local/share/X11/xsession";
            initExtra = "ERRFILE=$HOME/.local/share/X11/xsession-errors";
        };
        home = {
            packages = with pkgs; [
                #python310
                gnumake
                gcc
            ];
            persistence."/Storage/Apps/System/Cinnamon" = {
                # Loads persistent data for plank
                directories = [
                    ".config/cinnamon"
                    ".config/cinnamon-session"
                    ".local/share/cinnamon"
                ];
                files = [
                    ".config/X-Cinnamon-xdg-terminals.list"
                    ".config/xdg-terminals.list"
                    ".config/mimeapps.list"
                ];
                allowOther = true;
            };
        };
        systemd.user.services = {
            "cinnamon-spice-updater" = {
                Unit = {
                    Description = "Cinnamon Spice Updater";
                    After = "home-beatlink-.local-share-cinnamon.mount";
                };
                Service = {
                    ExecStart = "${pkgs.cinnamon-common}/bin/cinnamon-spice-updater --update-all";
                };
                Install = {
                    WantedBy = [ "default.target" ];
                };
            };
        };
    };
}
