# Cinnamon Settings
#
# This module configures all the settings for the Cinnamon Desktop Environment. Cinnamon settings are stored in dconf.
# It is automatically generated by nixtool's export dconf options so you can change the cinnamon settings then export the changes without editing
# the file manually.
#

{
    inputs,
    lib,
    pkgs,
    ...
}:
let
    webGreeter = inputs.web-greeter.packages.${pkgs.stdenv.hostPlatform.system}.web-greeter;
    halonGreeterTheme = inputs.halon.packages.${pkgs.stdenv.hostPlatform.system}.halon-lightdm-theme;
    # QtWebEngine's GPU compositor cannot make a Skia representation of its Ozone backing on this iGPU, so every
    # layer above the page background fails to paint and the greeter shows an empty screen; software compositing draws it.
    webGreeterWrapped = pkgs.writeShellScriptBin "web-greeter" ''
        export QTWEBENGINE_CHROMIUM_FLAGS="--disable-gpu-compositing ''${QTWEBENGINE_CHROMIUM_FLAGS:-}"
        exec ${webGreeter}/bin/web-greeter "$@"
    '';
    # LightDM starts the greeter from this desktop entry's Exec, so the wrapper only takes effect once the entry names it
    webGreeterXgreeters = pkgs.runCommand "web-greeter-xgreeters" { } ''
        mkdir -p "$out"
        substitute ${webGreeter.xgreeters}/web-greeter.desktop "$out/web-greeter.desktop" \
            --replace-fail "${webGreeter}/bin/web-greeter" "${webGreeterWrapped}/bin/web-greeter"
    '';
in
{
    imports = [ ./always-on-top.nix ];

    environment.sessionVariables = {
        NIXOS_OZONE_WL = "1"; # Read by the nixpkgs Chromium and Electron wrappers, which add their Wayland flags only when WAYLAND_DISPLAY is set too
        QT_QPA_PLATFORM = "wayland;xcb"; # Qt takes the entries in turn, so Qt 5 stops defaulting to xcb while keeping it as the fallback
    };

    services = {
        displayManager = {
            logToFile = false;
            logToJournal = false;
            defaultSession = "cinnamon-wayland"; # Per-output scanout buffers, so losing a monitor cannot wedge every head at once
            # LightDM reports a user's session from the AccountsService XSession key, and nixpkgs' set-session writes that key only for an X11
            # default, so a Wayland one leaves the last X11 session named there and web-greeter starts it in preference to the seat default.
            # The `|| true` matters: this runs in the pre-start script under set -e, where a failed call would leave the machine with no login at all.
            generic.preStart = lib.mkAfter ''
                user=/org/freedesktop/Accounts/User$(${pkgs.coreutils}/bin/id -u beatlink)
                ${pkgs.systemd}/bin/busctl call org.freedesktop.Accounts $user org.freedesktop.Accounts.User SetXSession s cinnamon-wayland || true
            '';
        };
        xserver = {
            enable = true; # Enables X11 Server
            displayManager.lightdm = {
                enable = true; # Enables LightDM Login Manager
                # Puts the graphical session on VT7 instead of VT1. NixOS defaults
                # minimum-vt to 1, which lands X on the same VT as the first getty
                # and makes Ctrl+Alt+F1..F6 unusable. This key is emitted after the
                # module's own, so it wins.
                extraConfig = ''
                    minimum-vt = 7
                '';
                # The seat default is only web-greeter's last fallback, behind the user's own AccountsService session, so it needs the stamp below.
                extraSeatDefaults = ''
                    user-session = cinnamon-wayland
                '';
                greeters.gtk.enable = false; # Defaults on, and its own greeter definition would collide with the one below
                # web-greeter has no NixOS module, so the greeter is named directly
                greeter = {
                    package = webGreeterXgreeters;
                    name = "web-greeter";
                };
            };
            desktopManager.cinnamon.enable = true; # Enables Cinnamon
            enableCtrlAltBackspace = true; # Enables CTRL+ALT+Backspace for restarting X11
            excludePackages = with pkgs; [ xterm ];
        };
        libinput.enable = true; # Enables Touchpad Functionality
    };
    # web-greeter reads this path unconditionally; it has no XDG or per-user lookup
    environment.etc."lightdm/web-greeter.toml".text = ''
        layouts = [ "us" ]

        [greeter]
        debug-mode = false
        detect-theme-errors = true
        screensaver-timeout = 300
        secure-mode = true
        theme = "${halonGreeterTheme.themePath}" # An absolute path, since the theme lives outside web-greeter's own themes directory
        icon-theme = "Bibata-Modern-Classic" # Named icon-theme, but the greeter only feeds it to XCURSOR_THEME

        [features.battery]
        enabled = true

        # Off because the greeter writes /sys/class/backlight directly, which the lightdm user cannot do
        [features.backlight]
        enabled = false
        value = 10
        steps = 0

        [branding]
        background-images-dir = "/run/current-system/sw/share/backgrounds"
        logo-image = "${webGreeter}/share/icons/hicolor/scalable/apps/com.github.jezerm.web-greeter.svg"
        user-image = "${webGreeter}/share/icons/hicolor/scalable/apps/com.github.jezerm.web-greeter.svg"
    '';

    themes.halon.enable = true; # Installs the GTK and Cinnamon theme; the exported dconf below is what selects it

    environment.systemPackages = with pkgs; [
        gnome-themes-extra
        libnotify
        ddcutil
        i2c-tools
        brightnessctl
        bibata-cursors # The greeter resolves its cursor through XCURSOR_PATH, which covers the system profile
    ];
    environment.cinnamon.excludePackages = with pkgs; [
        onboard
        gnome-calendar
        gnome-terminal
        warpinator
        celluloid
    ];

    home-manager.users.beatlink = {
        xsession = {
            scriptPath = ".local/share/X11/xsession";
            initExtra = "ERRFILE=$HOME/.local/share/X11/xsession-errors";
        };
        home = {
            packages = with pkgs; [
                #python310
                gnumake
                gcc
            ];
            persistence."/Storage/Apps/System/Cinnamon" = {
                # Loads persistent data for plank
                directories = [
                    ".config/cinnamon"
                    ".config/cinnamon-session"
                    ".local/share/cinnamon"
                ];
                files = [
                    ".config/X-Cinnamon-xdg-terminals.list"
                    ".config/xdg-terminals.list"
                    ".config/mimeapps.list"
                ];

            };
        };
        systemd.user.services = {
            "cinnamon-spice-updater" = {
                Unit = {
                    Description = "Cinnamon Spice Updater";
                    After = "home-beatlink-.local-share-cinnamon.mount";
                };
                Service = {
                    ExecStart = "${pkgs.cinnamon-common}/bin/cinnamon-spice-updater --update-all";
                };
                Install = {
                    WantedBy = [ "default.target" ];
                };
            };
        };
    };
}
