{
    imports = [
        ./hardware-configuration.nix
        ./root-drive-disko.nix
        ./software.nix
        ./networking.nix
        ./display.nix
        ./sensors.nix
        ./modem.nix
        ./clevis.nix
        ./initrd-wifi.nix
        ./power.nix
        ./keyboard.nix
        ./on-screen-keyboard.nix
        ./keyboard-firmware.nix
        ./kernel.nix
        ./phosh-bump.nix
        ./data-drive.nix
        ./mobile-data.nix
        ./performance.nix
        ./focus-boost.nix
        ./keyboard-layout
        ./audio.nix
        ./bluetooth.nix
        ./location.nix
        ./gpu-meter.nix
        ./webkit.nix
        ./launchapp.nix
        ./plymouth
        ./unl0kr.nix
        ./boot-leds.nix
        ./charging.nix
        ./arc-policy.nix
        ./theme.nix
        ./fn-lock.nix
        ./usb-networking.nix
        ./wireguard-watchdog.nix
    ];
}
