{
    imports = [
        ./1-hardware-configuration.nix
        ./3-root-drive-disko.nix
        ./4-software.nix
        ./5-networking.nix
        ./6-display.nix
        ./7-sensors.nix
        ./8-modem.nix
        ./9-clevis.nix
        ./10-initrd-wifi.nix
        ./11-power.nix
        ./12-keyboard.nix
        ./13-kernel.nix
        ./14-phosh-bump.nix
        ./15-data-drive.nix
        ./16-waydroid.nix
        ./17-mobile-data.nix
        ./18-performance.nix
        ./19-keyboard-layout
        ./21-audio.nix
    ];
}
