{
    imports = [
        ./hardware-configuration.nix
        ./boot.nix
        ./root-drive-disko.nix
        ./disko-data-drive.nix
        ./sops.nix
        ./software.nix
        ./networking.nix
        ./display.nix
        ./sound.nix
        ./bluetooth.nix
        ./printing.nix
        ./fuse.nix
        ./tang.nix
        ./desktop-environment
        ./remote-builder.nix
    ];
}
