{
    imports = [
        ./1-hardware-configuration.nix
        ./2-boot.nix
        ./3-root-drive-disko.nix
        ./4-disko-data-drive.nix
        ./5-sops.nix
        ./6-software.nix
        ./7-networking.nix
        ./8-display.nix
        ./9-sound.nix
        ./10-bluetooth.nix
        ./11-printing.nix
        ./12-fuse.nix
        ./13-home-folders.nix
        ./14-tang.nix
        ./15-codecs.nix
        ./16-plymouth.nix
        ./17-dconf
        ./18-desktop-environment
        ./19-thor-usb-link.nix
        ./20-nixtool.nix
        ./21-remote-builder.nix
    ];
}
