{
    imports = [
        ./hardware-configuration.nix
        ./filesystem.nix
        ./directories.nix
        ./performance.nix
        ./sops.nix
        ./boot-splash.nix
        ./software.nix
        ./networking.nix
        ./display.nix
        ./ideapad.nix
        ./sound.nix
        ./bluetooth.nix
        ./fuse.nix
        ./tang.nix
        ./desktop-environment
    ];
}
