# Cinnamon Settings
#
# This module configures all the settings for the Cinnamon Desktop Environment. Cinnamon settings are stored in dconf-settings.nix. 
# It is automatically generated by export-dconf-settings.sh so you can change the cinnamon settings then export the changes without editing
# the file manually. 
#

{  
    programs.dconf.enable = true;
    services.blueman.enable = true;
    home-manager.users.beatlink = {
        dconf.enable = true;                                                # Enables dconf for Cinnamon setting Management
        imports = [                                                         # Imports Cinnamon Dconf Settings
            ./2-dconf-settings.nix
        ];
    };
 }

