# Cinnamon Settings
#
# This module configures all the settings for the Cinnamon Desktop Environment. Cinnamon settings are stored in dconf-settings.nix. 
# It is automatically generated by export-dconf-settings.sh so you can change the cinnamon settings then export the changes without editing
# the file manually. 
#

{  
    programs.dconf.enable = true;
    services.blueman.enable = true;
    home-manager.users.beatlink = { pkgs, lib, ...}: {
        dconf.enable = true;                                                # Enables dconf for Cinnamon setting Management
        #imports = [                                                         # Imports Cinnamon Dconf Settings
        #    ./2-dconf-settings.nix
        #];
        home.activation.bluemanDconfLoad = lib.hm.dag.entryAfter ["xdg.configFile"] ''
            bluemanSettings=${builtins.toString (builtins.path {path = ./settings.dconf;})}
            if [ -f "$bluemanSettings" ]; then
                dconf load /org/blueman/ < "$bluemanSettings"
            fi
        '';
    };
 }

