# Cinnamon Settings
#
# This module configures all the settings for the Cinnamon Desktop Environment. Cinnamon settings are stored in dconf-settings.nix. 
# It is automatically generated by export-dconf-settings.sh so you can change the cinnamon settings then export the changes without editing
# the file manually. 
#

{  
    programs.dconf.enable = true;
    services.blueman.enable = true;
    home-manager.users.beatlink = {pkgs, lib, ...}: {
        home.packages = [pkgs.dconf];
        dconf.enable = true;                                               # Enables dconf for Cinnamon setting Management
        systemd.user.services.bluemanDconfLoad = {
            Unit = {
                Description = "Load Blueman dconf settings";
            };
            Service = {
                ExecStart = "${pkgs.bash}/bin/bash -c '${pkgs.dconf}/bin/dconf load /org/blueman/ < ${./settings.dconf}'";
                Type = "oneshot";
                RemainOnExit = true;
            };
            Install = {
                WantedBy = [ "default.target" ];
            };
        };
    
    };
}

