{
    imports = [
        ./calculator.nix
        ./cheese.nix
        ./czkawka.nix
        ./drawio.nix
        ./gallery-dl.nix
        ./inkscape.nix
        ./libreoffice.nix
        ./packet-tracer.nix
        ./separator.nix
        ./linux-sidebar.nix
        ./universal-android-debloater.nix
        ./video-downloader.nix
        ./virt-manager.nix
        ./wmctrl.nix
        ./xed.nix
        ./xviewer.nix
        ./fileroller
        ./pix
    ];
}
