{
    imports = [
        ./calculator.nix
        ./cheese.nix
        ./czkawka.nix
        ./deluge.nix
        ./drawio.nix
        ./dupeguru.nix
        ./gallery-dl.nix
        ./inkscape.nix
        ./libreoffice.nix
        ./screenshot.nix
        ./simple-scan.nix
        ./universal-android-debloater.nix
        #./ventoy.nix
        ./video-downloader.nix
        ./virt-manager.nix
        ./wmctrl.nix
        ./xed.nix
        ./xviewer.nix
        ./pix
    ];
}
